version: '3.9'

services:
  worker: &worker
      build: .
      volumes:
          - static_dir:/app/static
          - ./media:/media
          - .:/app

  web:
      <<: *worker
      command: >
          bash -c " pip install -r requirements.txt &&
                    python manage.py makemigrations &&
                    python manage.py migrate &&
                    gunicorn --bind 0.0.0.0:8001 ekkbazz.wsgi --reload
                  "
      expose:
          - "8001:8001"
      restart: always


  nginx:
    build: ./nginx/
    ports: 
      - 80:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - static_dir:/home/app/static
    depends_on:
      - web


volumes:
  static_dir: