version: '3.9'

services:
  worker: &worker
      build: .
      volumes:
          - static_dir:/app/static
          - ./media:/media
          - .:/app
      environment:
          - DATABASE_URL=postgres://postgres:postgres@db:5432/ekkbazz_database
          - DATABASE_NAME=ekkbazz_database
          - DATABASE_USER=admin
          - DATABASE_PASSWORD=admin
          - DATABASE_HOST=db
          - DATABASE_PORT=5432

  web:
      <<: *worker
      command: >
          bash -c " pip install -r requirements.txt &&
                    python manage.py makemigrations &&
                    python manage.py migrate &&
                    gunicorn --bind 0.0.0.0:8001 ekkbazz.wsgi --reload
                  "
      expose:
          - "8001:8001"
      restart: always
      depends_on:
          - db

  db:
      image: postgres:14.1
      environment:
          - POSTGRES_USER=${DATABASE_USER:-admin}
          - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-admin}
          - POSTGRES_DB=ekkbazz_database
          - PGDATA=/var/lib/postgresql/data/pgdata
      volumes:
          - pgdata:/var/lib/postgresql/data/pgdata
      ports:
          - "5432:5432"


  nginx:
    build: ./nginx/
    ports: 
      - 80:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - static_dir:/home/app/static
    depends_on:
      - web


volumes:
  static_dir:
  pgdata: