# Generated by Django 4.1.6 on 2023-02-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=50, verbose_name='Business Name')),
                ('place_name', models.CharField(max_length=70, verbose_name='Place Name')),
                ('latitude', models.DecimalField(blank=True, decimal_places=25, max_digits=30, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=25, max_digits=30, null=True, verbose_name='Longitude')),
            ],
            options={
                'verbose_name_plural': 'Business',
                'db_table': 'Business',
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
