# Generated by Django 4.1.6 on 2023-02-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='latitude',
            field=models.DecimalField(decimal_places=25, max_digits=30, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='business',
            name='longitude',
            field=models.DecimalField(decimal_places=25, max_digits=30, null=True, verbose_name='Longitude'),
        ),
    ]
